apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${{ values.app_name }}
  name: ${{ values.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.app_name }}
  template:
    metadata:
      labels:
        app: ${{ values.app_name }}
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/quarkusdroneshop-demo/reward
        name: ${{ values.app_name }}
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP