apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: s2i-${{ values.app_name }}-run
spec:
  pipelineRef:
    name: s2i-build-and-deploy
  params:
    - name: GIT_REPO
      value: https://github.com/${{ values.git_owner_name }}/${{ values.git_repo_name }}.git
    - name: IMAGE_NAME
      value: image-registry.openshift-image-registry.svc:5000/your-namespace/${{ values.app_name }}
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: s2i-pvc-${{ values.app_name }}
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi