apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: tekton-trigger-template
  title: Tekton + Trigger Template
  description: BackstageからTriggerでPipelineRun実行
spec:
  owner: user:default/nmushino
  type: service

  parameters:
    - title: アプリケーション情報
      required: [app_name, git_owner_name, git_repo_name]
      properties:
        app_name: { type: string }
        git_owner_name: { type: string }
        git_repo_name: { type: string }
        image_tag: { type: string, default: latest }

    - title: Tekton情報
      required: [tektonNamespace, clusterDomain, tektonToken]
      properties:
        tektonNamespace: { type: string, default: quarkusdroneshop-cicd }
        clusterDomain:
          type: string
          description: apps.<cluster-domain>
          default: apps.ocp.hfczn.sandbox2320.opentlc.com
        tektonToken:
          type: string
          description: "Tekton Listener 認証トークン"

    - title: 所有者情報
      required: [owner]
      properties:
        owner:
          type: string
          ui:field: EntityPicker
          ui:options:
            allowedKinds: [User]

  steps:
    - id: fetch
      name: テンプレート取得
      action: fetch:template
      input:
        url: ./skeleton
        values:
          app_name: ${{ parameters.app_name }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: GitHubへPush
      action: publish:github
      input:
        repoUrl: github.com?owner=${{ parameters.git_owner_name }}&repo=${{ parameters.git_repo_name }}
        defaultBranch: main
        repoVisibility: public

    - id: create-pvc
      name: Shared Workspace PVC作成
      action: http:backstage:request
      input:
        method: POST
        path: /proxy/kubernetes-api/api/v1/namespaces/${{ parameters.tektonNamespace }}/persistentvolumeclaims
        headers:
          Content-Type: application/json
        continueOnBadResponse: true
        body:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: ${{ parameters.app_name }}-shared-workspace-pvc
            namespace: ${{ parameters.tektonNamespace }}
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi

    - id: create-pipelinerun
      name: PipelineRun実行
      action: http:backstage:request
      input:
        method: POST
        path: /proxy/kubernetes-api/apis/tekton.dev/v1/namespaces/${{ parameters.tektonNamespace }}/pipelineruns
        headers:
          Content-Type: application/json
        body:
          apiVersion: tekton.dev/v1
          kind: PipelineRun
          metadata:
            generateName: ${{ parameters.app_name }}-
            namespace: ${{ parameters.tektonNamespace }}
          spec:
            pipelineRef:
              name: ${{ parameters.app_name }}
            workspaces:
              - name: shared-workspace
                persistentVolumeClaim:
                  claimName: ${{ parameters.app_name }}-shared-workspace-pvc
              - name: dependency-check-cache
                persistentVolumeClaim:
                  claimName: dependency-check-db

  output:
    links:
      - title: GitHub Repository
        url: ${{ steps['publish'].output.remoteUrl }}

      - title: OpenShift Pipelines
        url: https://console-openshift-console.${{ parameters.clusterDomain }}/k8s/ns/${{ parameters.tektonNamespace }}/tekton.dev~v1~PipelineRun