apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: quarkus-s2i-template
  title: Quarkus S2I App Template
  description: Quarkus アプリケーションを S2I でビルド＆OpenShiftにデプロイ
spec:
  owner: user:guest
  type: service

  parameters:
    - title: アプリケーション情報
      required:
        - app_name
        - git_owner_name
        - git_repo_name
      properties:
        app_name:
          type: string
          title: アプリケーション名
        git_owner_name:
          type: string
          title: GitHub オーナー名
        git_repo_name:
          type: string
          title: GitHub リポジトリ名

  steps:
    - id: fetch
      name: テンプレート取得
      action: fetch:template
      input:
        url: ./skeleton
        values:
          app_name: ${{ parameters.app_name }}
          git_owner_name: ${{ parameters.git_owner_name }}
          git_repo_name: ${{ parameters.git_repo_name }}

    - id: publish
      name: GitHubへPush
      action: publish:github
      input:
        repoUrl: github.com?owner=${{ parameters.git_owner_name }}&repo=${{ parameters.git_repo_name }}
        sourcePath: .
        defaultBranch: main
        protectDefaultBranch: false
        description: Generated Quarkus app with S2I pipeline

    - id: register
      name: Backstageに登録
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: GitHub リポジトリ
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Backstage エンティティ
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}