apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  description: Rewardのマイクロサービスです
  labels:
    app: reward
  annotations:
    backstage.io/kubernetes-id: ${{ values.app_name }}
    argocd/app-selector: app.kubernetes.io/instance=${{ values.app_name }}-init
    tektonci.io/pipeline: ${{ values.app_name }}
    tekton.dev/type: pipeline
    rhdh.redhat.com/tekton-enabled: "true"
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
  system: ${{ values.cluster_name }}