apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  description: "${{ values.app_name }} のマイクロサービスです"
  tags:
    - ${{ values.image_tag }}
    - ${{ values.system_name }}
  labels:
    app: ${{ values.app_name }}
  annotations:
    backstage.io/kubernetes-id: ${{ values.app_name }}
    backstage.io/kubernetes-namespace: quarkusdroneshop-demo
    backstage.io/kubernetes-cluster: ${{ values.system_name }}
    backstage.io/kubernetes-label-selector: app=${{ values.app_name }}
    argocd/app-selector: app.kubernetes.io/instance=${{ values.app_name }}-init
    tektonci.io/pipeline: ${{ values.app_name }}
    tekton.dev/type: pipeline
    rhdh.redhat.com/tekton-enabled: "true"
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
  system: ${{ values.system_name }}