apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusdroneshop-${{ values.app_name }}
  description: "quarkusdroneshop-${{ values.app_name }} のマイクロサービスです"
  tags:
    - ${{ values.image_tag }}
    - ${{ values.system_name }}
  labels:
    app: ${{ values.app_name }}
  annotations:
    backstage.io/kubernetes-id: quarkusdroneshop-${{ values.app_name }}
    backstage.io/kubernetes-namespace: quarkusdroneshop-cicd
    backstage.io/kubernetes-cluster: ${{ values.system_name }}
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=quarkusdroneshop-${{ values.app_name }}
    argocd/app-selector: app.kubernetes.io/instance=quarkusdroneshop-${{ values.app_name }}
    tektonci.io/pipeline: build-and-push-quarkusdroneshop-${{ values.app_name }}
    tektonci.io/pipelineNamespace: quarkusdroneshop-cicd
    tekton.dev/type: pipeline
    tekton.dev/cicd: "true"
    janus-idp.io/tekton: "true"
    rhdh.redhat.com/tekton-enabled: "true"
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
  system: ${{ values.system_name }}
