apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ${app_name}
  namespace: quarkusdroneshop-demo
  labels:
    app: ${app_name}
spec:
  to:
    kind: Service
    name: ${app_name}
  port:
    targetPort: 8080
  tls:
    termination: edge