apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-quarkusdroneshop-${{ values.app_name }}
  namespace: quarkusdroneshop-cicd
  labels:
    app: quarkusdroneshop-${{ values.app_name }}
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/quarkusdroneshop/quarkusdroneshop-reward'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: maven-run
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven-no-settings21
      params:
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value: "clean verify -Dquarkus.package.jar.type=uber-jar"
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: push-oc-apps
      runAfter:
        - maven-run
      taskRef:
        name: push-app-task
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            set -e

            APP=${{ values.app_name }}
            oc delete all -l app=$APP -n quarkusdroneshop-demo || true
            oc delete bc/quarkusdroneshop-$APP -n quarkusdroneshop-demo || true

            RUNNER_JAR=$(ls target/*-runner.jar | head -1)
            oc new-build --binary --name=quarkusdroneshop-$APP --docker-image=registry.access.redhat.com/ubi8/openjdk-21:1.20 -n quarkusdroneshop-demo
            oc patch bc/quarkusdroneshop-$APP -n quarkusdroneshop-demo --type=json -p '[{"op":"replace","path":"/spec/strategy/sourceStrategy/from","value":{"kind":"DockerImage","name":"registry.access.redhat.com/ubi8/openjdk-21:1.20"}}]'
            oc start-build quarkusdroneshop-$APP --from-file="$RUNNER_JAR" --follow -n quarkusdroneshop-demo
            oc new-app $APP --name=quarkusdroneshop-$APP --allow-missing-images -n quarkusdroneshop-demo
            oc set env deployment/quarkusdroneshop-$APP JAVA_OPTS_APPEND="-Dquarkus.profile=prod" -n quarkusdroneshop-demo

            PGSQL_URL=$(oc get configmap droneshop-config -n quarkusdroneshop-demo -o=jsonpath='{.data.PGSQL_URL}')
            oc set env deployment/quarkusdroneshop-$APP PGSQL_URL=$PGSQL_URL -n quarkusdroneshop-demo
            PGSQL_USER=$(oc get secret droneshopdb-pguser-droneshopadmin -n quarkusdroneshop-demo -o=jsonpath='{.data.user}' | base64 --decode)
            oc set env deployment/quarkusdroneshop-$APP PGSQL_USER=$PGSQL_USER -n quarkusdroneshop-demo
            PGSQL_PASS=$(oc get secret droneshopdb-pguser-droneshopadmin -n quarkusdroneshop-demo -o=jsonpath='{.data.password}' | base64 --decode)
            oc set env deployment/quarkusdroneshop-$APP PGSQL_PASS=$PGSQL_PASS -n quarkusdroneshop-demo

            KAFKA_URL=$(oc get configmap droneshop-config -n quarkusdroneshop-demo -o=jsonpath='{.data.KAFKA_BOOTSTRAP_URLS}')
            oc set env deployment/quarkusdroneshop-$APP KAFKA_BOOTSTRAP_URLS=$KAFKA_URL -n quarkusdroneshop-demo
            QUARKUS_LOG_LEVEL=$(oc get configmap droneshop-config -n quarkusdroneshop-demo -o=jsonpath='{.data.QUARKUS_LOG_LEVEL}')
            oc set env deployment/quarkusdroneshop-$APP QUARKUS_LOG_LEVEL=$QUARKUS_LOG_LEVEL -n quarkusdroneshop-demo
      workspaces:
        - name: source
          workspace: shared-workspace