apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: quarkusdroneshop-reward
  title: quarkusdroneshop-reward app
  description: rewardのscaffolderマイクロサービス
  tags:
    - recommended
spec:
  owner: user:default/nmushino
  type: service

  parameters:
    - title: rewardのマイクロサービス
      required:
        - app_name
        - owner
      properties:
        app_name:
          title: quarkusdroneshop-reward
          description: 作成するアプリ名を指定してください。
          type: string
          default: "quarkusdroneshop-reward"
        owner:
          title: オーナー
          type: string
          description: 作成するComponentのオーナーを選択してください。
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
    - title: GitHubリポジトリ
      required:
        - git_repo_name
        - git_host_url
        - git_owner_name
      properties:
        git_repo_name:
          title: GitHubリポジトリ名
          description: 生成するGitHubリポジトリ名を入力してください。
          type: string
          default: quarkusdroneshop-reward
        git_host_url:
          title: GitHub URL
          description: GitHubリポジトリの情報を入力してください。
          type: string
          default: github.com?owner=quarkusdroneshop&repo=quarkusdroneshop-reward
        git_owner_name:
          title: GitHub Organization名
          description: GitHubリポジトリを生成するGitHub Organization名を入力してください。
          type: string
          default: quarkusdroneshop
    - title: Kafka Topics
      required:
        - topic-incoming
        - topic-outgoing
      properties:
        topic-incoming:
          title: 入力トピック名
          description: インプットとなるトピック名を入力してください。
          type: string
          default: 
        topic-outgoing:
          title: 出力トピック名
          description: アウトプットとなるトピック名を入力してください。
          type: string
          default: 

  steps:
    - id: fetch
      name: Fetch skeleton 
      action: fetch:template
      input:
        url: ./manifest-skeleton
        values:
          app_name: ${{ parameters.app_name }}
          owner: ${{ parameters.owner }}
          git_repo_name: ${{ parameters.git_repo_name }}
          git_host_url: ${{ parameters.git_host_url }}
          git_owner_name: ${{ parameters.git_owner_name }}
          topic-incoming: ${{ parameters.topic-incoming }}
          topic-outgoing: ${{ parameters.topic-outgoing }}
        targetPath: ./tenant

    - id: publish
      name: Push to GitHub 
      action: publish:github
      input:
        repoUrl: github.com?owner=${{ parameters.git_owner_name }}&repo=${{ parameters.git_repo_name }}
        repoVisibility: public
        sourcePath: ./tenant
        defaultBranch: develop
        protectDefaultBranch: false

    - id: deploy
      name: Trigger S2I Pipeline
      action: kubernetes:apply
      input:
        manifest:
          apiVersion: tekton.dev/v1beta1
          kind: PipelineRun
          metadata:
            generateName: s2i-build-
          spec:
            pipelineRef:
              name: s2i-java-pipeline
            params:
              - name: IMAGE
                value: image-registry.openshift-image-registry.svc:5000/quarkusdroneshop-demo/${{ parameters.app_name }}
              - name: GIT_REPO
                value: https://github.com/nmushino/${{ parameters.app_name }}
            workspaces:
              - name: shared-workspace
                persistentVolumeClaim:
                  claimName: quarkusdroneshop-${{ parameters.app_name }}-pvc

    - id: argocd
      name: Deploy with ArgoCD
      action: argocd:create-resources
      input:
        appName: ${{ parameters.app_name }}-init
        argoInstance: main
        namespace: openshift-gitops
        repoUrl: https://${{ parameters.git_host_url }}/${{ parameters.git_owner_name }}/${{ parameters.git_repo_name }}.git
        path: 'argocd/'

    - id: register
      name: Register Catalog into Developer Hub 
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Component
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: Gitリポジトリ
        url: ${{ steps['publish'].output.remoteUrl }}
        icon: github