apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ${app_name}
  namespace: quarkusdroneshop-demo
  labels:
    app: ${app_name}
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: "https://github.com/quarkusdroneshop/${app_name}.git"
      ref: main
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'redhat-openjdk18-openshift:1.9'
        namespace: openshift
      env:
        - name: MAVEN_ARGS_APPEND
          value: "-DskipTests"
  output:
    to:
      kind: ImageStreamTag
      name: "${app_name}:latest"
  triggers:
    - type: GitHub
      github:
        secret: 4b9aece50d51e45c8a46ae7db1b7f0c00a3a7995
    - type: ConfigChange
    - type: ImageChange