apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app_name}
  namespace: quarkusdroneshop-demo
  labels:
    app: ${app_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${app_name}
  template:
    metadata:
      labels:
        app: ${app_name}
    spec:
      containers:
        - name: ${app_name}
          image: image-registry.openshift-image-registry.svc:5000/quarkusdroneshop-demo/${app_name}:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTIONS
              value: "-Xmx512m"