apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: ${{ values.app_name }}
  name: ${{ values.app_name }}
  namespace: quarkusdroneshop-demo
spec:
  lookupPolicy:
    local: true