apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  backstage.io/kubernetes-id: ${{ values.app_name }}

resources:
  - deployment.yaml
  - imagestream.yaml
  - service.yaml
  - route.yaml