apiVersion: v1
kind: Service
metadata:
    app: ${{ values.app_name }}
  name: ${{ values.app_name }}
  namespace: quarkusdroneshop-demo
spec:
  selector:
    app: ${{ values.app_name }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP